name: Manual Deployment to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Publish Project
      run: dotnet publish --configuration Release
      working-directory: NightOwlEnterprise/src/NightOwlEnterprise.Api

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "EC2IP -> ${{ secrets.EC2_IP }}"
        echo "SSH_PRIVATE_KEY ->  ${{ secrets.EC2_SSH_PRIVATE_KEY }}"
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H {{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
