name: Manual Deployment to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Publish Project
      run: dotnet publish --configuration Release
      working-directory: NightOwlEnterprise/src/NightOwlEnterprise.Api
